version: '3.7'

services:
  users-service:
    build:
      context: ./users-service
    ports:
      - "8000:8000"
    volumes:
      - ./users-service:/app
    depends_on:
      - message-broker

  notifications-service:
    build:
      context: ./notifications-service
    ports:
      - "8001:8000"
    volumes:
      - ./notifications-service:/app
      - ./notifications-service/logs:/app/logs
    depends_on:
      - message-broker

  message-broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  users-worker:
    build:
      context: ./users-service
    command: ["php", "bin/console", "messenger:consume", "async", "-vv"]
    depends_on:
      message-broker:
        condition: service_healthy
      users-service:
        condition: service_started
